version: "3.9"

x-environment:
  &default-environment
  - POSTGRES_DB=postgres
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres

services:
  marketplace_db:
    image: postgres
    ports:
      - "5431:5432"
    environment: *default-environment
  marketplace_web:
    build:
      context: .
      dockerfile: marketplace/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./marketplace:/code
    ports:
      - "8000:8000"
    depends_on:
      - marketplace_db
  catalogs_db:
    image: postgres
    ports:
      - "5432:5432"
    environment: *default-environment
  catalogs_web:
    build:
      context: .
      dockerfile: catalogs/Dockerfile
    command: python manage.py grpcrunserver --dev
    volumes:
      - ./catalogs:/code
    ports:
      - "8001:8000"
    depends_on:
      - catalogs_db
  orders_db:
    image: postgres
    ports:
      - "5433:5432"
    environment: *default-environment
  orders_web:
    build:
      context: .
      dockerfile: orders/Dockerfile
    command: python manage.py grpcrunserver --dev
    volumes:
      - ./orders:/code
    ports:
      - "8002:8000"
    depends_on:
      - orders_db
