# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalogs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='catalogs.proto',
  package='catalogs',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63\x61talogs.proto\x12\x08\x63\x61talogs\x1a\x1bgoogle/protobuf/empty.proto\"2\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\x14\n\x12ProductListRequest\"$\n\x16ProductRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xaf\x02\n\x11ProductController\x12;\n\x04List\x12\x1c.catalogs.ProductListRequest\x1a\x11.catalogs.Product\"\x00\x30\x01\x12\x30\n\x06\x43reate\x12\x11.catalogs.Product\x1a\x11.catalogs.Product\"\x00\x12\x41\n\x08Retrieve\x12 .catalogs.ProductRetrieveRequest\x1a\x11.catalogs.Product\"\x00\x12\x30\n\x06Update\x12\x11.catalogs.Product\x1a\x11.catalogs.Product\"\x00\x12\x36\n\x07\x44\x65stroy\x12\x11.catalogs.Product\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='catalogs.Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='catalogs.Product.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='catalogs.Product.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='catalogs.Product.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=107,
)


_PRODUCTLISTREQUEST = _descriptor.Descriptor(
  name='ProductListRequest',
  full_name='catalogs.ProductListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=129,
)


_PRODUCTRETRIEVEREQUEST = _descriptor.Descriptor(
  name='ProductRetrieveRequest',
  full_name='catalogs.ProductRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='catalogs.ProductRetrieveRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=167,
)

DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
DESCRIPTOR.message_types_by_name['ProductListRequest'] = _PRODUCTLISTREQUEST
DESCRIPTOR.message_types_by_name['ProductRetrieveRequest'] = _PRODUCTRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'catalogs_pb2'
  # @@protoc_insertion_point(class_scope:catalogs.Product)
  })
_sym_db.RegisterMessage(Product)

ProductListRequest = _reflection.GeneratedProtocolMessageType('ProductListRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTLISTREQUEST,
  '__module__' : 'catalogs_pb2'
  # @@protoc_insertion_point(class_scope:catalogs.ProductListRequest)
  })
_sym_db.RegisterMessage(ProductListRequest)

ProductRetrieveRequest = _reflection.GeneratedProtocolMessageType('ProductRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTRETRIEVEREQUEST,
  '__module__' : 'catalogs_pb2'
  # @@protoc_insertion_point(class_scope:catalogs.ProductRetrieveRequest)
  })
_sym_db.RegisterMessage(ProductRetrieveRequest)



_PRODUCTCONTROLLER = _descriptor.ServiceDescriptor(
  name='ProductController',
  full_name='catalogs.ProductController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=170,
  serialized_end=473,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='catalogs.ProductController.List',
    index=0,
    containing_service=None,
    input_type=_PRODUCTLISTREQUEST,
    output_type=_PRODUCT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='catalogs.ProductController.Create',
    index=1,
    containing_service=None,
    input_type=_PRODUCT,
    output_type=_PRODUCT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='catalogs.ProductController.Retrieve',
    index=2,
    containing_service=None,
    input_type=_PRODUCTRETRIEVEREQUEST,
    output_type=_PRODUCT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='catalogs.ProductController.Update',
    index=3,
    containing_service=None,
    input_type=_PRODUCT,
    output_type=_PRODUCT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='catalogs.ProductController.Destroy',
    index=4,
    containing_service=None,
    input_type=_PRODUCT,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTCONTROLLER)

DESCRIPTOR.services_by_name['ProductController'] = _PRODUCTCONTROLLER

# @@protoc_insertion_point(module_scope)
