# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: items.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='items.proto',
  package='items',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bitems.proto\x12\x05items\x1a\x1bgoogle/protobuf/empty.proto\"G\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x12\n\nproduct_id\x18\x03 \x01(\x05\x12\r\n\x05order\x18\x04 \x01(\x05\"\x11\n\x0fItemListRequest\"!\n\x13ItemRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xf6\x01\n\x0eItemController\x12/\n\x04List\x12\x16.items.ItemListRequest\x1a\x0b.items.Item\"\x00\x30\x01\x12$\n\x06\x43reate\x12\x0b.items.Item\x1a\x0b.items.Item\"\x00\x12\x35\n\x08Retrieve\x12\x1a.items.ItemRetrieveRequest\x1a\x0b.items.Item\"\x00\x12$\n\x06Update\x12\x0b.items.Item\x1a\x0b.items.Item\"\x00\x12\x30\n\x07\x44\x65stroy\x12\x0b.items.Item\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='items.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='items.Item.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='items.Item.quantity', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='items.Item.product_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order', full_name='items.Item.order', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=122,
)


_ITEMLISTREQUEST = _descriptor.Descriptor(
  name='ItemListRequest',
  full_name='items.ItemListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=141,
)


_ITEMRETRIEVEREQUEST = _descriptor.Descriptor(
  name='ItemRetrieveRequest',
  full_name='items.ItemRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='items.ItemRetrieveRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=176,
)

DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['ItemListRequest'] = _ITEMLISTREQUEST
DESCRIPTOR.message_types_by_name['ItemRetrieveRequest'] = _ITEMRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'items_pb2'
  # @@protoc_insertion_point(class_scope:items.Item)
  })
_sym_db.RegisterMessage(Item)

ItemListRequest = _reflection.GeneratedProtocolMessageType('ItemListRequest', (_message.Message,), {
  'DESCRIPTOR' : _ITEMLISTREQUEST,
  '__module__' : 'items_pb2'
  # @@protoc_insertion_point(class_scope:items.ItemListRequest)
  })
_sym_db.RegisterMessage(ItemListRequest)

ItemRetrieveRequest = _reflection.GeneratedProtocolMessageType('ItemRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _ITEMRETRIEVEREQUEST,
  '__module__' : 'items_pb2'
  # @@protoc_insertion_point(class_scope:items.ItemRetrieveRequest)
  })
_sym_db.RegisterMessage(ItemRetrieveRequest)



_ITEMCONTROLLER = _descriptor.ServiceDescriptor(
  name='ItemController',
  full_name='items.ItemController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=179,
  serialized_end=425,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='items.ItemController.List',
    index=0,
    containing_service=None,
    input_type=_ITEMLISTREQUEST,
    output_type=_ITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='items.ItemController.Create',
    index=1,
    containing_service=None,
    input_type=_ITEM,
    output_type=_ITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='items.ItemController.Retrieve',
    index=2,
    containing_service=None,
    input_type=_ITEMRETRIEVEREQUEST,
    output_type=_ITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='items.ItemController.Update',
    index=3,
    containing_service=None,
    input_type=_ITEM,
    output_type=_ITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='items.ItemController.Destroy',
    index=4,
    containing_service=None,
    input_type=_ITEM,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ITEMCONTROLLER)

DESCRIPTOR.services_by_name['ItemController'] = _ITEMCONTROLLER

# @@protoc_insertion_point(module_scope)
